[package]
name = "aoc2020"
version = "0.1.0"
authors = ["blair"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
regex = "1"
either = "1.6.1"
num-bigint = "0.3"